rss:
  # - https://www.rbc.ua/static/rss/newsline.img.rus.rss.xml
  # - https://www.rbc.ua/static/rss/newsline.img.ukr.rss.xml
  # - https://www.liga.net/rss-page
  # - https://www.pravda.com.ua/rus/rss-info/
  - https://rss.unian.net/site/news_rus.rss
  # - https://bin.ua/news/rss.xml
  # - https://www.eurointegration.com.ua/rus/rss-info/
  # - https://inform-ua.info/rss-list