rss:
  - https://www.rbc.ua/ukr/rss.shtml
  - https://www.liga.net/rss-page
  - https://www.pravda.com.ua/rus/rss-info/
  - https://rss.unian.net/site/news_rus.rss
  - https://bin.ua/news/rss.xml
  - https://www.eurointegration.com.ua/rus/rss-info/
https://inform-ua.info/rss-list